"""empty message

Revision ID: 72488102da10
Revises: 636ab9a1c4c1
Create Date: 2024-01-09 18:59:06.459648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72488102da10'
down_revision = '636ab9a1c4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('reg_no',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('reg_no',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
